teamsNames = ["Perú", "Argentina", "Paraguay", "Uruguay", "Brasil", "Venezuela", "Colombia", "Ecuador", "Chile", "Bolivia"]
from ..entity import Team

TEAMS = []
TEAMS.append("")
for i in range(0,len(teamsNames)): TEAMS.append(Team(teamsNames[i]))

MATCHES = (
[(TEAMS[3],TEAMS[1]),(TEAMS[4],TEAMS[9]),(TEAMS[2],TEAMS[8]),(TEAMS[7],TEAMS[6]),(TEAMS[5],TEAMS[10])],
[(TEAMS[6],TEAMS[3]),(TEAMS[8],TEAMS[4]),(TEAMS[10],TEAMS[2]),(TEAMS[9],TEAMS[7]),(TEAMS[1],TEAMS[5])],
[(TEAMS[10],TEAMS[8]),(TEAMS[2],TEAMS[3]),(TEAMS[7],TEAMS[4]),(TEAMS[9],TEAMS[1]),(TEAMS[5],TEAMS[6])],
[(TEAMS[4],TEAMS[5]),(TEAMS[1],TEAMS[2]),(TEAMS[6],TEAMS[9]),(TEAMS[3],TEAMS[10]),(TEAMS[8],TEAMS[7])],
[(TEAMS[7],TEAMS[5]),(TEAMS[6],TEAMS[8]),(TEAMS[10],TEAMS[1]),(TEAMS[2],TEAMS[4]),(TEAMS[9],TEAMS[3])],
[(TEAMS[4],TEAMS[10]),(TEAMS[1],TEAMS[6]),(TEAMS[5],TEAMS[2]),(TEAMS[3],TEAMS[7]),(TEAMS[8],TEAMS[9])],
[(TEAMS[4],TEAMS[3]),(TEAMS[1],TEAMS[7]),(TEAMS[5],TEAMS[8]),(TEAMS[10],TEAMS[6]),(TEAMS[2],TEAMS[9])],
[(TEAMS[7],TEAMS[2]),(TEAMS[6],TEAMS[4]),(TEAMS[3],TEAMS[5]),(TEAMS[9],TEAMS[10]),(TEAMS[8],TEAMS[1])],
[(TEAMS[1],TEAMS[4]),(TEAMS[6],TEAMS[2]),(TEAMS[10],TEAMS[7]),(TEAMS[9],TEAMS[5]),(TEAMS[8],TEAMS[3])],
[(TEAMS[4],TEAMS[8]),(TEAMS[7],TEAMS[9]),(TEAMS[5],TEAMS[1]),(TEAMS[3],TEAMS[6]),(TEAMS[2],TEAMS[10])],
[(TEAMS[4],TEAMS[7]),(TEAMS[1],TEAMS[9]),(TEAMS[6],TEAMS[5]),(TEAMS[3],TEAMS[2]),(TEAMS[8],TEAMS[10])],
[(TEAMS[7],TEAMS[8]),(TEAMS[5],TEAMS[4]),(TEAMS[10],TEAMS[3]),(TEAMS[2],TEAMS[1]),(TEAMS[9],TEAMS[6])],
[(TEAMS[4],TEAMS[2]),(TEAMS[1],TEAMS[10]),(TEAMS[5],TEAMS[7]),(TEAMS[3],TEAMS[9]),(TEAMS[8],TEAMS[6])],
[(TEAMS[7],TEAMS[3]),(TEAMS[6],TEAMS[1]),(TEAMS[10],TEAMS[4]),(TEAMS[2],TEAMS[5]),(TEAMS[9],TEAMS[8])],
[(TEAMS[7],TEAMS[1]),(TEAMS[6],TEAMS[10]),(TEAMS[3],TEAMS[4]),(TEAMS[9],TEAMS[2]),(TEAMS[8],TEAMS[5])],
[(TEAMS[4],TEAMS[6]),(TEAMS[1],TEAMS[8]),(TEAMS[5],TEAMS[3]),(TEAMS[10],TEAMS[9]),(TEAMS[2],TEAMS[7])],
[(TEAMS[4],TEAMS[1]),(TEAMS[7],TEAMS[10]),(TEAMS[5],TEAMS[9]),(TEAMS[3],TEAMS[8]),(TEAMS[2],TEAMS[6])],
[(TEAMS[1],TEAMS[3]),(TEAMS[6],TEAMS[7]),(TEAMS[10],TEAMS[5]),(TEAMS[9],TEAMS[4]),(TEAMS[8],TEAMS[2])]
)